## *Sesión de retos*

### Objetivo de la Sesión 3:

* Repasar NumPy resolviendo algunos ejercicios.
* Repasar Pandas resolviendo algunos ejercicios.

### *“Trabajar en equipo, divide el trabajo y multiplica los resultados”*, Anónimo.

In [2]:
import numpy as np
import pandas as pd

# 1. NumPy

1. Muestra la versión de NumPy utilizada

In [3]:
np.version.version

'1.18.1'

2. Crear un arreglo 1D con enteros positivos aleatorios

In [3]:
rando_ints = np.random.randint(0, 255, 255)
rando_ints

array([ 26, 145, 190, 126, 172,  35, 250, 156, 241, 151,  75, 146,   7,
       117,  35, 162, 235, 201, 241, 183, 194, 138,  39,  89,   8,  73,
        91,  34,   0, 220, 101, 207, 234,  90, 250, 118,   4, 117, 180,
        62, 136, 179, 189, 229, 238,  56, 226,  83, 252, 201, 228, 231,
       237, 121, 144,  53, 125, 161,  13, 128,   6, 137,   1, 101,  94,
       228, 187, 248,  81, 245, 173, 207,   4,   5, 168, 244,  17,  71,
        86, 116,  21, 177, 111,  43, 175,  75,  87, 245,  19,  96, 217,
       226, 219, 251,  71, 245,  53,  71, 251, 118, 196, 149,  75, 247,
       226, 147,  69,  25,   0,  22, 129,  18, 124,  86,  20,  73, 184,
       230, 216, 193, 148,  13, 205, 219,  25,   6, 234, 151, 134, 194,
        70, 164, 182, 155, 180, 197,  92, 237,  17, 159, 124, 180,  78,
       198, 195, 133, 150, 185,  73, 126, 162, 106, 123, 231, 153, 135,
       242, 177, 246, 156, 113,  23, 234,  58,  87, 126, 123, 239, 163,
        64, 222, 151, 112,  22,  96,   9,  87, 100,  35, 199, 10

3. Crear un arreglo booleano

In [4]:
random_array = np.random.choice([False, True],6)
random_array

array([False,  True,  True, False,  True, False])

4. Extraer los items que sean divisibles en 3.

In [5]:
items = np.random.randint(0,255, 10)
divisible_by_3 = items[items % 3 == 0]
divisible_by_3

array([18,  3, 15])

5. Convierte el arreglo booleano de 1D a 2D con tres filas (*reshape*)

In [6]:
np.reshape(random_array, [3, 2])

array([[False,  True],
       [ True, False],
       [ True, False]])

6. Obtén los items comunes entre dos arreglos

In [7]:
a = np.random.randint(0, 10, 10)
b = np.random.randint(0, 10, 10)
np.intersect1d(a, b)

array([0, 1, 3, 8, 9])

7. Extrae los números del vector creado en el ejercicio 2 que esten a dos números de distancia del valor promedio del arreglo.

In [8]:
rando_ints1 = rando_ints[rando_ints >= (rando_ints.mean() - 2)]
rando_ints1[rando_ints1 <= (rando_ints.mean() + 2)]

array([134, 133, 135])

8. Muestra solo 3 decimales en un vector.

In [9]:
v = np.random.randn(10)
np.around(v, decimals=3)

array([ 0.184,  1.354,  0.102, -0.663,  0.897, -2.279, -0.138,  1.206,
       -2.459, -0.786])

9. Crea una atriz de 3x3 con los valores del 0 a 8

In [10]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Del siguiente areglo [1,2,0,0,4,] encuentra los índices donde los elementos sean diferente a cero.

In [11]:
c = np.array([1,2,0,0,4])
np.where(c != 0)

(array([0, 1, 4], dtype=int64),)

11. Crea un vector aleatorio de 30 elementos y encuentra la media.

In [12]:
d = np.random.randint(0, 255, 30)
d.mean()

124.73333333333333

12. Crea un arreglo 2D con 1 en los bordes y 0 dentro. Por ejemplo:
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1

In [13]:
h = np.ones((5,5))
h[1:-1,1:-1] = 0
h

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

13. ¿Cuál es el resultado de la siguiente expresión?

`0 * np.nan`

`np.nan == np.nan`

`np.inf > np.nan`

`np.nan - np.nan`

`np.nan in set([np.nan])`

`0.3 == 3 * 0.1`

In [117]:
print(0 * np.nan) # Cualquier valor por NaN sigue siendo NaN

print(np.nan == np.nan) # NaN no es lo mismo que NaN, ya que no es un numero

print(np.inf > np.nan) # Infinito no puede ser mayor que NaN porque no es un numero e infinito si

print(np.nan - np.nan) # NaN - NaN es NaN

print(np.nan in set([np.nan])) # Esto da true por que nan esta dentro de los elementos del arreglo

print(0.3 == 3 * 0.1) # No son iguales porque son puntos flotantes

nan
False
False
nan
True
False



14. Crea una matriz de 5x5 con valores 1, 2, 3, 4 justo después de la diagonal.

In [5]:
i = np.random.randint(low=2,high=50,size=(5,5))
for x in range(4):
    i[x][x + 1] = x + 1
i

j = np.random.randint(10,50,(5,5))
diag = np.arange(4)
j[diag, diag + 1] = [1,2,3,4]
j

array([[39,  1, 37, 16, 25],
       [42, 37,  2, 27, 37],
       [48, 39, 38,  3, 18],
       [15, 42, 29, 30,  4],
       [12, 46, 11, 35, 42]])

15. Normaliza una matriz aleatoria de 5x5

In [119]:
e = np.random.randint(0, 25, 25).reshape(5, 5)
row_sums = e.sum(axis=1)
f = e / row_sums[:, np.newaxis]
f

array([[0.11320755, 0.        , 0.35849057, 0.22641509, 0.30188679],
       [0.04255319, 0.08510638, 0.44680851, 0.        , 0.42553191],
       [0.2       , 0.18571429, 0.05714286, 0.28571429, 0.27142857],
       [0.20689655, 0.05172414, 0.34482759, 0.27586207, 0.12068966],
       [0.05479452, 0.32876712, 0.30136986, 0.17808219, 0.1369863 ]])

# 2. Pandas

1. Imprime toda la información de versión de las librerias que necesita la biblioteca de pangas.

In [49]:
pd.__version__
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : None
python           : 3.7.6.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
machine          : AMD64
processor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.0.0
numpy            : 1.18.1
pytz             : 2019.3
dateutil         : 2.8.1
pip              : 20.0.2
setuptools       : 45.1.0.post20200127
Cython           : 0.29.14
pytest           : 5.3.5
hypothesis       : 5.4.1
sphinx           : 2.3.1
blosc            : None
feather          : None
xlsxwriter       : 1.2.7
lxml.etree       : 4.5.0
html5lib         : 1.0.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.1
IPython          : 7.12.0
pandas_datareader: None
bs4              : 4.8.2
bottleneck       : 1.3.1
fastparquet      : None
gcsfs            : None
lxml.etree       :

Considera el siguiente diccionario y lista.


```
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

2. Crea un DataFrame con el diccionario *data* que tenga como índices los valores de la lista *labels*.

In [7]:
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df0 = pd.DataFrame(data, index=labels)
df0

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

3. Muestra una descripción o información básica acerca del DataFrame y sus datos. (Pista: existe una función que lo muestra).

In [54]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


4. Regresa las primeras 3 filas del DataFrame

In [57]:
df0.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

5. Cambia el nombre de las columnas por:


*   Animal
*   Edad
*   Visitas
*   Prioridad



In [8]:
df0.columns = ['Animal', 'Edad', 'Visitas', 'Prioridad']
df0

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
c  snake   0.5        2        no
d    dog   NaN        3       yes
e    dog   5.0        2        no
f    cat   2.0        3        no
g  snake   4.5        1        no
h    cat   NaN        1       yes
i    dog   7.0        2        no
j    dog   3.0        1        no

6. Muestra solo la columna "animal" and "age". ¿Esto es posible? Si no es posible, ¿qué debería ser?

In [124]:
df0[["Animal", "Edad"]]

Animal  Edad
a    cat   2.5
b    cat   3.0
c  snake   0.5
d    dog   NaN
e    dog   5.0
f    cat   2.0
g  snake   4.5
h    cat   NaN
i    dog   7.0
j    dog   3.0

7. Selecciona solo las filas donde el número de visitas sea mayor que 3.

In [21]:
df0.loc[df0["Visitas"] >= 3]

Animal  Edad  Visitas Prioridad
b    cat   3.0        3       yes
d    dog   NaN        3       yes
f    cat   2.0        3        no

8. ¿Cuáles son las filas donde la edad es NaN?

In [22]:
df0.loc[df0["Edad"].isna()]

Animal  Edad  Visitas Prioridad
d    dog   NaN        3       yes
h    cat   NaN        1       yes

9. ¿Qué animales tienen una edad entre 2 y 4 años?

In [24]:
df0.loc[(df0["Edad"] >= 2) & (df0["Edad"] <= 4)]

Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
f    cat   2.0        3        no
j    dog   3.0        1        no

10. ¿Cuál es el total de todas las visitas?

In [27]:
df0["Visitas"].sum()

19

12. Tenemos diferentes animales, ¿cuál es el número total de cada tipo de animal?

In [13]:
df0.groupby("Animal")["Animal"].value_counts()

Animal  Animal
cat     cat       4
dog     dog       4
snake   snake     2
Name: Animal, dtype: int64

13. Cambia los valores de la columna Prioridad por valores booleanos, es decir:
'yes' => True 
'no' => False

In [18]:
df0["Prioridad"].replace({"yes": True, "no": False}, inplace=True)
df0

Animal  Edad  Visitas  Prioridad
a    cat   2.5        1       True
b    cat   3.0        3       True
c  snake   0.5        2      False
d    dog   NaN        3       True
e    dog   5.0        2      False
f    cat   2.0        3      False
g  snake   4.5        1      False
h    cat   NaN        1       True
i    dog   7.0        2      False
j    dog   3.0        1      False

14. Ordena el DataFrame por la Edad en orden descendiente y después por la columna Visitas en orden ascendente.

In [29]:
df0.sort_values(["Edad", "Visitas"], ascending=[False, True])

Animal  Edad  Visitas  Prioridad
i    dog   7.0        2      False
e    dog   5.0        2      False
g  snake   4.5        1      False
j    dog   3.0        1      False
b    cat   3.0        3       True
a    cat   2.5        1       True
f    cat   2.0        3      False
c  snake   0.5        2      False
h    cat   NaN        1       True
d    dog   NaN        3       True

15. Para cada tipo de animal y cada número de visitas encuentra la edad promedio. 
(Pista: Si haz utilizado tablas pivotes, cada fila es un animal, cada columna es el número de visitas y los valores son la media de la edad).

In [31]:
df0.groupby(['Animal','Visitas']).mean()

Edad  Prioridad
Animal Visitas                 
cat    1         2.5        1.0
       3         2.5        0.5
dog    1         3.0        0.0
       2         6.0        0.0
       3         NaN        1.0
snake  1         4.5        0.0
       2         0.5        0.0

# 3. Retos (opcional)

- Random Walk

- Game of Life

- Imagenes

- Texto